version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "9090:9090"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
